Update masterfhirvalidation.yml

diff --git a/.github/workflows/masterfhirvalidation.yml b/.github/workflows/masterfhirvalidation.yml
--- a/.github/workflows/masterfhirvalidation.yml
+++ b/.github/workflows/masterfhirvalidation.yml
@@ -67,9 +67,20 @@ jobs:
         run: cd validation-service-fhir-r4 && mvn clean package
 
       - name: Run FHIR Validator
-        run: 
+        run: |
           nohup java -jar validation-service-fhir-r4/target/fhir-validator.jar --terminology.url=https://ontology.nhs.uk/production1/fhir --terminology.authorization.tokenUrl=https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token --terminology.authorization.clientId=${{ secrets.ONTO_CLIENT_ID }} --terminology.authorization.clientSecret=${{ secrets.ONTO_CLIENT_SECRET }} --aws.validationSupport=false --aws.queueEnabled=false &
-          sleep 200
+          # Wait for it to become ready, try 30 times, with 10 seconds between
+          for i in {1..30}; do
+            if curl -sSf http://localhost:8080/fhir/metadata > /dev/null; then
+              echo "FHIR Validator is up!"
+              exit 0
+            fi
+            echo "Waiting for FHIR Validator..."
+            sleep 10
+          done
+
+          echo "FHIR Validator failed to start in time"
+          exit 1
         
       - name: Run Test
         run: cd validation && npm test
